### ISSUE TITLE
retaining image repo names in kbld packaging workflow

### ISSUE THREAD

**Issue by datianshi** [carvel-dev/kbld#31]
When you package. I wonder why this does not do repo name to repo name map. Instead, it pushed into the same repo

https://github.com/k14s/kbld/blob/develop/docs/packaging.md

``Images will be imported under a single new repository docker.io/dkalinin/app1. You are guaranteed that images are exactly same as they are referenced by the same digests in produced YAML configuration (though under a different repository name).```

**Comment by cppforlife** [comment]
how would you avoid naming conflicts between various image names (eg lots of things could have a image name called "webhook")? (additionally it's not possible in some cases to retain names given RBAC rules of registry or various registries supporting arbitrary paths vs not).

i would also question need for retaining names since humans shouldn't be looking at image refs manually but rather rely on a tool to tell them what images are in use. arguably even then, why does it matter what image is in use, since configuration bundle (that carries image references) is what ultimately matters. im eager to hear your thoughts on these points.

**Comment by datianshi** [comment]
@cppforlife I thought this is based on the hash. So no conflicts? 

My simply use case is that. I have many k8s manifests depends on registry 1. I want to package them locally and upload to the other offline/internal registry. And I can template/replace my manifest with the new registry url

**Comment by cppforlife** [comment]
> I thought this is based on the hash. So no conflicts?

the digest does identify image uniquely however it's confusing that unrelated projects may end up using same repo name (e.g. my-private-reg.com/dkalinin/webhook@sha256:..., in this case, whose webhook are we talking about) since their name could be the same. with current behaviour since all images referenced by config are uploaded to a single repo, you can for example delete that repo when you no longer need that project (without guessing which images to delete).

> My simply use case is that. I have many k8s manifests depends on registry 1. I want to package them locally and upload to the other offline/internal registry.

that's exactly how kbld package/unpackage is meant to be used for.

> And I can template/replace my manifest with the new registry url

instead of manually templating things we expect people to rely on kbld to update image references with new urls. docs/packaging.md shows that as an example. any reason why that doesnt work for you?

**Comment by datianshi** [comment]
cool I got your point @cppforlife basically using kbld and the manifest.lock (one generated during unpack) to interoperate the manifest files again.

**Comment by cppforlife** [comment]
that's right.

**Comment by cppforlife** [comment]
closing. question was answered it seems.
