### ISSUE TITLE
Containerd mess with kbld

### ISSUE THREAD

**Issue by pgossa** [carvel-dev/kbld#310]
**What steps did you take:**
I am trying to build and deploy an application using ytt, kapp and kbld.  
Kbld use kubectl buildkit to build the image which goes fine.  
Then when kapp try to deploy the container, the container goes in a Back-off pulling image state.

**What happened:**
Kapp get stuck trying to retrieve the image.  
```Pending: ImagePullBackOff (message: Back-off pulling image "kbld:rand-1673529450859089537-1671522333694-sitepro")```

**Anything else you would like to add:**
Final line of kbld building: ```final: sitepro -> kbld:rand-1673529450859089537-1671522333694-sitepro```
I can find the image in containerd using: ```sudo ctr -n k8s.io i ls | grep sitepro```
Which result in:
```
kbld:rand-1673529450859089537-1671522333694-sitepro
application/vnd.docker.distribution.manifest.v2+json
sha256:f5f935d85a6fdb9223cd8ab136f9822f61db7edd69dc72a23a5d25f0832167ca 
26.7 MiB 
linux/amd64 
io.cri-containerd.image=managed
```

**Environment:**

- kbld version 0.36.1
- Not using registry
- Debian 11

Buildkit:
- Client:  v0.1.6
- Builder: buildkitd github.com/moby/buildkit v0.11.0 830288a71f447b46ad44ad5f7bd45148ec450d44

Kubernetes version: 
- Client Version: v1.26.0
- Server Version: v1.26.0
- Kubeadm Version v1.26.0
- Containerd Version 1.6.15

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.

**Comment by joaopapereira** [comment]
Hello, @pgossa thanks for reaching out.
Does the cluster have access to the containerd "registry"?
Usually, when you use kbld to build your image you can go with one of 2 approaches
1 - Give access to the daemon/local registry you build the images on
2 - You push the image to a registry that the k8s cluster that has access to.

We usually suggest that you do number 2 since it is a more "realistic" scenario and is not always easy or acceptable to share the daemon/local registry with the cluster. You can see an example https://carvel.dev/kbld/docs/v0.36.0/building/#pushing-images of how to push images
